# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skedr
# "service" is the name of this project. This will also be added to your AWS resource names.
app: code-challenge
service: code-challenge-5

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: functions/handler.hello
    events:
      - httpApi:
          path: /
          method: get
