name: Serverless actions 
on: [push, pull_request]
jobs:

  deploy:
    name: Execute actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v4

      - name: Deploy service
        run: |
          pnpm install
          pnpm sls deploy