name: Removes Serverless 
on:
  pull_request:
    types: [closed]
    
jobs:

  deploy:
    name: Execute actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v4

      - name: Determine branch name
        id: branch_name
        run: echo "STAGE=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          

      - name: Remove service
        env:
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        run: |
          pnpm install
          pnpm sls remove --stage=$STAGE